### PR TITLE
Add a calendar list view

### PR DESCRIPTION
**Pull request by hd1ex**
This change introduces list views. They are mostly a copy of the day views.

### CODE REVIEW

**Comment by schliz** [comment]
finally 🙏

**Comment by vongaisberg** [comment]
lgtm

**Comment by hd1ex** [comment]
Has anyone had the time to review this? Is there something I can do to get this done soon?

**Comment by Tjeri** [comment]
Could you elaborate, what exactly this is supposed to do and solve. Maybe attach a screenshot to show?
There is no explanation in here.

**Comment by schliz** [comment]
I have tested this again and everything seems to work. The left filter view in the calendar is still very messy but this is a problem for another time.

@Tjeri if you still have any input regarding this PR, I am happy to hear it.

@hd1ex thank you for your contribution, I'll go ahead and merge.

**Pull request merged**
